# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mendis\Documents\GitHub\DRAGON-VOICEMODE\overlay_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from time import time
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from win32api import GetSystemMetrics
from PyQt5.QtCore import QSettings
import time
import global_hotkey_sys
import overlay_dialog_py

class overlaydialog(QtWidgets.QMainWindow, overlay_dialog_py.Ui_Dialog):
    def __init__(self, parent=None):
        super (overlaydialog, self).__init__(parent)
        self.setupUi(self)

class keyboardlistenerto_openoverlaydailog_thread(QtCore.QThread):
    when_OD_hotkeypressed = QtCore.pyqtSignal(str)
    def __init__(self,parent=None):
        super(keyboardlistenerto_openoverlaydailog_thread,self).__init__(parent)

    def run(self):
        print("dalidala")
        def on_OD_hotkeypressed(pessedkey):
            print(pessedkey+" rimmpanaaia")
            self.when_OD_hotkeypressed.emit(pessedkey)

        ghs3 = global_hotkey_sys.globalhotkeysys()
        ghs3.start_listen(onpresshotkeycall = on_OD_hotkeypressed)

class getaudiostats_thread(QtCore.QThread):
    audiostat = QtCore.pyqtSignal(str)
    def __init__(self, parent=None):
        super(getaudiostats_thread,self).__init__(parent)
    def run(self):
        self.settingval = QSettings("Dragon Voide Mode","settings vals")
        while True:
            time.sleep(0.02)
            self.audiostat.emit(str(self.settingval.value("audio_stat")))
            


class Ui_overlay(object):
    def setupUi(self, overlay):
        overlay.setObjectName("overlay")
        self.w = GetSystemMetrics(0)
        self.h = GetSystemMetrics(1)
        overlay.resize(int(self.w), int(self.h))
        self.stats = QtWidgets.QLabel(overlay)
        self.stats.setGeometry(QtCore.QRect(20, 20, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stats.setFont(font)
        self.stats.setScaledContents(True)
        self.stats.setObjectName("stats")
        self.stats.setAttribute(Qt.WA_TransparentForMouseEvents,True)
        self.stats.setMouseTracking(False)
        self.stats.setAttribute(Qt.WA_TranslucentBackground,True)
        print("Width =", self.w)
        print("Height =", self.h)
        self.settingval = QSettings("Dragon Voide Mode","settings vals")
        self.settingval.setValue("audio_stat","Idle")
        print("overlaystarted")
        self.stats.setText(str(self.settingval.value("audio_stat")))
        
        self.retranslateUi(overlay)
        self.show_stats()
        self.startlistnertoODhotkey()
        QtCore.QMetaObject.connectSlotsByName(overlay)

    def show_stats(self):
        print("show stats")
        self.t1 = getaudiostats_thread()
        self.t1.start()
        self.t1.audiostat.connect(self.stats.setText)

    def startlistnertoODhotkey(self):
        print("chchchc")
        self.thread_ODhotkey = keyboardlistenerto_openoverlaydailog_thread()
        self.thread_ODhotkey.start()
        self.thread_ODhotkey.when_OD_hotkeypressed.connect(self.call_overlaydailog)    
    
    def call_overlaydailog(self,pressedkey):
        print(pressedkey+" nananani")
        #self.settingval.value("overlaydialoghotkey")
        OD_hotkey = self.settingval.value("overlaydialoghotkey") #("hotkeyfor overlay dailog")
        self.dialog = overlaydialog(None)
        if pressedkey == OD_hotkey:
            print("open overlay 1")
            self.dialog.show()  
    def retranslateUi(self, overlay):
        _translate = QtCore.QCoreApplication.translate
        overlay.setWindowTitle(_translate("overlay", "overlay"))
        #self.stats.setText(_translate("overlay", "statics"))

    


if __name__ == "__main__":
#def openoverlay():    
    import sys
    app = QtWidgets.QApplication(sys.argv)
    overlay = QtWidgets.QDialog()
    overlay.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.FramelessWindowHint )#| Qt.X11BypassWindowManagerHint)
    overlay.setAttribute(Qt.WA_TransparentForMouseEvents,True)
    overlay.setAttribute(Qt.WA_TranslucentBackground,True)
    overlay.setAttribute(Qt.WA_X11DoNotAcceptFocus,True) 
    #overlay.setAttribute(Qt.WA_X11TransparentForInput,True)
    ui = Ui_overlay()
    ui.setupUi(overlay)
    overlay.show()
    sys.exit(app.exec_())

