# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mendis\Documents\GitHub\DRAGON-VOICEMODE\overlay_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

class Ui_overlay(object):
    def setupUi(self, overlay):
        overlay.setObjectName("overlay")
        overlay.resize(756, 545)
        self.stats = QtWidgets.QLabel(overlay)
        self.stats.setGeometry(QtCore.QRect(20, 20, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.stats.setFont(font)
        self.stats.setScaledContents(True)
        self.stats.setObjectName("stats")
        self.stats.setAttribute(Qt.WA_TransparentForMouseEvents,True)
        

        self.retranslateUi(overlay)
        QtCore.QMetaObject.connectSlotsByName(overlay)

    def retranslateUi(self, overlay):
        _translate = QtCore.QCoreApplication.translate
        overlay.setWindowTitle(_translate("overlay", "overlay"))
        self.stats.setText(_translate("overlay", "statics"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    overlay = QtWidgets.QDialog()
    overlay.setWindowFlags(Qt.WindowStaysOnTopHint | Qt.FramelessWindowHint )#| Qt.X11BypassWindowManagerHint)
    overlay.setAttribute(Qt.WA_TransparentForMouseEvents,True)
    overlay.setAttribute(Qt.WA_TranslucentBackground,True)
    overlay.setAttribute(Qt.WA_X11DoNotAcceptFocus,True) 
    overlay.setAttribute(Qt.WA_X11TransparentForInput,True)
    ui = Ui_overlay()
    ui.setupUi(overlay)
    overlay.show()
    sys.exit(app.exec_())
