# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voice mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from PyQt5.QtCore import QSettings
import pathlib
import sounddevice as sd
import pyaudio
import audio
import re
import pickle
import globle_key_listener
import mic_to_output


global mydir
mydir = os.path.dirname(os.path.realpath(__file__))
global audiofiledir
audiofiledir = [""]
global userpath
userpath =os.path.expanduser('~')
global selectedaudios
selectedaudios = []
global deviceslistin
deviceslistin =[]
global deviceslistout
deviceslistout =[]
global deviceslist
deviceslist =[]
global hotkeydict
hotkeydict ={}
global selectedoutdeviceindex
selectedoutdeviceindex = [0]
global selectedindeviceindex
selectedindeviceindex = [0]
global modifirekeyslist
modifirekeyslist = ['Key.alt_l','Key.alt_gr']

class mictoout_thread(QtCore.QThread):
    
    def __init__(self,selectedinputdevice,selectedoutputdevice, parent=None):
        super(mictoout_thread,self).__init__(parent)
        self.selectedinputd = selectedinputdevice
        self.selectedoutputd =selectedoutputdevice
    def run(self):
        try:
            mic_to_output.startmictooutput(self.selectedinputd,self.selectedoutputd)
        except:
            print("print err")    

class gblkeylistener_thread(QtCore.QThread):
    
    def __init__(self, parent=None):
        super(gblkeylistener_thread,self).__init__(parent)
    def run(self):
        globle_key_listener.starlistener(hotkeydict,selectedoutdeviceindex[0])

class Ui_voicemode(object):
    def setupUi(self, voicemode):
        voicemode.setObjectName("voicemode")
        voicemode.resize(642, 540)
        self.makesettingvals()        
        self.setdefsettingvals()
        self.getsettingvals()
        print(selectedoutdeviceindex[0])
        try:
            datainfile = pickle.load(open(mydir+"/"+"saves/hotkeys.dvm","rb")) #read data in file
            print(datainfile)
            hotkeydictinfile = datainfile
            hotkeydict.update(hotkeydictinfile)
            print(hotkeydict)
        except:
            pass
        self.centralwidget = QtWidgets.QWidget(voicemode)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 651, 461))
        self.tabWidget.setObjectName("tabWidget")
        self.soundboard = QtWidgets.QWidget()
        self.soundboard.setObjectName("soundboard")
        self.asinghk = QtWidgets.QPushButton(self.soundboard)
        self.asinghk.setGeometry(QtCore.QRect(10, 10, 121, 41))
        self.asinghk.setObjectName("asinghk")
        self.asinghk.clicked.connect(self.asinghk_clk)
        self.comboBox = QtWidgets.QComboBox(self.soundboard)
        self.comboBox.setGeometry(QtCore.QRect(10, 60, 51, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.soundboard)
        self.lineEdit.setGeometry(QtCore.QRect(90, 60, 41, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.soundboard)
        self.label.setGeometry(QtCore.QRect(70, 60, 16, 21))
        self.label.setObjectName("label")
        self.removehk = QtWidgets.QPushButton(self.soundboard)
        self.removehk.setGeometry(QtCore.QRect(10, 90, 121, 41))
        self.removehk.setObjectName("removehk")
        self.repeat = QtWidgets.QCheckBox(self.soundboard)
        self.repeat.setGeometry(QtCore.QRect(10, 140, 101, 17))
        self.repeat.setObjectName("repeat")
        self.listView = QtWidgets.QListView(self.soundboard)
        self.listView.setGeometry(QtCore.QRect(180, 10, 450, 400))
        self.listView.setObjectName("listView")
        self.refreshlist = QtWidgets.QPushButton(self.soundboard)
        self.refreshlist.setObjectName(u"refreshlist")
        self.refreshlist.setGeometry(QtCore.QRect(10, 160, 121, 23))
        self.refreshlist.clicked.connect(self.refreshlistfunc)
        self.tabWidget.addTab(self.soundboard, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalSlider = QtWidgets.QSlider(self.tab_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 30, 451, 22))
        self.horizontalSlider.setMaximum(4096)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.sampelrate = QtWidgets.QLabel(self.tab_2)
        self.sampelrate.setGeometry(QtCore.QRect(10, 0, 151, 21))
        self.sampelrate.setObjectName("sampelrate")
        self.tabWidget.addTab(self.tab_2, "")
        voicemode.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(voicemode)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 642, 21))
        self.menubar.setObjectName("menubar")
        self.about = QtWidgets.QMenu(self.menubar)
        self.about.setObjectName("about")
        voicemode.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(voicemode)
        self.statusbar.setObjectName("statusbar")
        voicemode.setStatusBar(self.statusbar)
        self.menubar.addAction(self.about.menuAction())
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QtCore.QRect(10, 70, 451, 21))
        self.label_2.setText(audiofiledir[0])
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QtCore.QRect(10, 470, 31, 21))
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QtCore.QRect(326, 470, 41, 21))
        self.openaudiopath = QtWidgets.QPushButton(self.tab_2)
        self.openaudiopath.setObjectName(u"openaudiopath")
        self.openaudiopath.setGeometry(QtCore.QRect(490, 70, 121, 23))
        self.openaudiopath.clicked.connect(self.getaudiofiledir)
        self.inputdevice = QtWidgets.QComboBox(self.centralwidget)
        self.inputdevice.setObjectName(u"inputdevice")
        self.inputdevice.setGeometry(QtCore.QRect(50, 470, 261, 22))
        self.outputdevice = QtWidgets.QComboBox(self.centralwidget)
        self.outputdevice.setObjectName(u"outputdevice")
        self.outputdevice.setGeometry(QtCore.QRect(370, 470, 261, 22))
           
        self.play = QtWidgets.QPushButton(self.soundboard)
        self.play.setObjectName(u"play")
        self.play.setGeometry(QtCore.QRect(10, 190, 41, 23))
        self.play.clicked.connect(self.play_clk)
        self.stop = QtWidgets.QPushButton(self.soundboard)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QtCore.QRect(90, 190, 41, 23))
        print(audiofiledir[0])
        self.getaudiolist()
        self.getaudiodevices()
        
        try:
            print(selectedoutdeviceindex[0])
            self.outputdevice.setCurrentIndex(selectedoutdeviceindex[0])
        except:
            pass
        self.outputdevice.currentTextChanged.connect(self.setdeviceindexfunc)
        try:
            print(selectedindeviceindex[0])
            self.inputdevice.setCurrentIndex(selectedindeviceindex[0])
        except:
            pass
        self.inputdevice.currentTextChanged.connect(self.setindeviceindexfunc)  
        self.retranslateUi(voicemode)
        self.tabWidget.setCurrentIndex(0)
        self.hotkeylistenercall()
        self.mictooutputcall()
        self.hearituself()
        QtCore.QMetaObject.connectSlotsByName(voicemode)

    def hearituself(self):
        self.thread3 = mictoout_thread(selectedinputdevice=deviceslist.index(sd.query_devices(kind='input')['name']),selectedoutputdevice=deviceslist.index(sd.query_devices(kind='output')['name']))
        self.thread3.start()

    def mictooutputcall(self):
        self.thread2 = mictoout_thread(selectedinputdevice=selectedindeviceindex[0],selectedoutputdevice=selectedoutdeviceindex[0])
        self.thread2.start()

    def hotkeylistenercall(self):
        self.thread1 = gblkeylistener_thread()
        self.thread1.start()

    def makesettingvals(self):
        self.settingval = QSettings("Dragon Voide Mode","settings vals")

    def setdefsettingvals(self):
        settingkeylist = self.settingval.allKeys()
        #print(str(len(settingkeylist)))
        if(settingkeylist == None):
            print("making regedit")
            self.settingval.setValue("audio path",userpath+"/Music")
            self.settingval.setValue("selectedoutdeviceindex",0)
            self.settingval.setValue("selectedindeviceindex",0)
        
        elif len(settingkeylist)==0:
            print("set def val")
            self.settingval.setValue("audio path",userpath+"/Music")
            self.settingval.setValue("selectedoutdeviceindex",0)
            self.settingval.setValue("selectedindeviceindex",0)
    def getsettingvals(self):
        self.settingval = QSettings("Dragon Voide Mode","settings vals")
        audiofiledir[0] = str(self.settingval.value("audio path"))
        selectedoutdeviceindex[0] = self.settingval.value("selectedoutdeviceindex")
        selectedindeviceindex[0] = self.settingval.value("selectedindeviceindex")

    def setsettingvals(self):
        self.settingval = QSettings("Dragon Voide Mode","settings vals")
        self.settingval.setValue("selectedoutdeviceindex",selectedoutdeviceindex[0])
        self.settingval.setValue("selectedindeviceindex",selectedindeviceindex[0])

    def getaudiofiledir(self):
        audiofiledir[0] = QtWidgets.QFileDialog.getExistingDirectory(None, 'audio folder path',mydir)
        self.label_2.setText(audiofiledir[0])
        self.settingval.setValue("audio path",audiofiledir[0])

    def getaudiolist(self):
        list_of_files = []
        list_of_Afiles = []
        for root, dirs, files in os.walk(audiofiledir[0]):
            for file in files:
                list_of_files.append(os.path.join(root,file))

        for i in list_of_files:
            file_extension = pathlib.Path(i).suffix
            print("File Extension: ", file_extension)
            if file_extension == ".wav":
                list_of_Afiles.append(i)
        self.listviwer(list_of_Afiles)    
    
    def listviwer(self,afilelist):
        """this func getting key of videodic and creating listview with checkbox"""
        global model
        model = QtGui.QStandardItemModel()
        for i in afilelist:
            print(i)
            item = QtGui.QStandardItem(i)
            check = QtCore.Qt.Checked = False
            item.setCheckState(check)
            item.setText(str(i))
            print(item.text()+" lisetview"+" "+str(item.checkState()))
            item.setCheckable(True)
            model.appendRow(item)
            print(model)
        self.listView.setModel(model)                        

    def refreshlistfunc(self):
        self.getaudiolist()

    def getaudiodevices(self):
        print("gettting audio devices")
        p = pyaudio.PyAudio()
        #deviceslist = []
        deviceslist.clear()
        for i in sd.query_devices():
            deviceslist.append(i['name'])
        #print(sd.query_devices(kind='input'))
        for i in range(len(deviceslist)):
            try:
                if sd.query_devices(i,'input')['max_input_channels']>0:
                    #print(sd.query_devices(i,'input')['name'])
                    deviceslistin.append(sd.query_devices(i,'input')['name'])
            except:
                pass
        print(deviceslistin)        
        for i in range(len(deviceslist)):
                
            try:
                if sd.query_devices(i,'output')['max_output_channels']>0:
                    #print(sd.query_devices(i,'output')['name'])
                    deviceslistout.append(sd.query_devices(i,'output')['name'])
            except:
                pass    
        print(deviceslistout)            
        self.inputdevice.addItems(deviceslistin)
        self.outputdevice.addItems(deviceslistout)

    def play_clk(self):
        self.getcheckditems(model)
        print(selectedaudios)
        selecetedfilepath = selectedaudios[0].replace('\\','/')
        print(selecetedfilepath)
        audio.playaudio(selecetedfilepath,deviceslist.index(self.outputdevice.currentText()),1024)
    
    def getcheckditems(self,models):
        selectedaudios.clear()
        for index in range(models.rowCount()):
            item = models.item(index)
            print(str(QtCore.Qt.Checked))
            if item.checkState() != QtCore.Qt.Checked:
                print(item.text()+" getcheck"+" "+str(item.checkState()))
                i = item.text()
                selectedaudios.append(i)
                #selectedvideos.append(item.text()    
        print(selectedaudios)
    
    def setdeviceindexfunc(self,text):
        print(text)
        dindex = selectedoutdeviceindex[0]
        if text in deviceslist:
            dindex = deviceslist.index(text)
            print("index of text"+str(dindex))
        selectedoutdeviceindex[0] = dindex
        self.setsettingvals() 

    def setindeviceindexfunc(self,text):
        print(str(type(deviceslist)))
        dindex = selectedindeviceindex[0]
        if text in deviceslist:
            dindex = deviceslist.index(text)
            print("index of text"+str(dindex))
        selectedindeviceindex[0] = dindex
        
        self.setsettingvals()

    def asinghk_clk(self):
        hkstr = self.lineEdit.text()
        print(hkstr)
        newhklist =[modifirekeyslist[self.comboBox.currentIndex()],hkstr]
        print(newhklist)
        newhk = newhklist[0]+"+"+newhklist[1]
        self.getcheckditems(model)
        hotkeydict[str(newhk)] = selectedaudios[0]
        print(hotkeydict)
        print("save kotkeys in to HDD")
        print(mydir)
        path =  mydir+"/saves"
        if os.path.exists(path)==False:
            print("not exist have to create")  
            os.mkdir(path)
            pickle.dump((hotkeydict),open(path+"/hotkeys"+".dvm","wb"))
            print("saving to "+str(path))
        else:
            pickle.dump((hotkeydict),open(path+"/hotkeys"+".dvm","wb"))
            print("saving to "+str(path))

    def retranslateUi(self, voicemode):
        _translate = QtCore.QCoreApplication.translate
        voicemode.setWindowTitle(_translate("voicemode", "DRAGON VOICE MODE"))
        self.asinghk.setText(_translate("voicemode", "Add Hot Key"))
        self.comboBox.setItemText(1, _translate("voicemode", "alt_r"))
        self.comboBox.setItemText(0, _translate("voicemode", "alt_l"))
        self.label.setText(_translate("voicemode", "+"))
        self.removehk.setText(_translate("voicemode", "Remove Hot Key"))
        self.repeat.setText(_translate("voicemode", "repeat"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.soundboard), _translate("voicemode", "Sound Board"))
        self.sampelrate.setText(_translate("voicemode", "sample rate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("voicemode", "Tab 2"))
        self.about.setTitle(_translate("voicemode", "about"))
        self.openaudiopath.setText(_translate("voicemode", u"open audio files dir", None))
        self.refreshlist.setText(_translate("voicemode", u"Refresh List", None))
        self.play.setText(_translate("voicemode", u"play", None))
        self.stop.setText(_translate("voicemode", u"stop", None))
        self.label_3.setText(_translate("voicemode", u"input", None))
        self.label_4.setText(_translate("voicemode", u"output", None))
        #self.label_2.setText(_translate("voicemode", u"TextLabel", None))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    voicemode = QtWidgets.QMainWindow()
    ui = Ui_voicemode()
    ui.setupUi(voicemode)
    voicemode.show()
    sys.exit(app.exec_())
