# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mendis\Documents\GitHub\DRAGON-VOICEMODE\overlay_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(845, 679)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 100, 821, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(0, 20, 821, 471))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.hearmyselfvolume_sb = QtWidgets.QSpinBox(Dialog)
        self.hearmyselfvolume_sb.setGeometry(QtCore.QRect(20, 50, 81, 31))
        self.hearmyselfvolume_sb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hearmyselfvolume_sb.setMaximum(200)
        self.hearmyselfvolume_sb.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.hearmyselfvolume_sb.setObjectName("hearmyselfvolume_sb")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(130, 50, 191, 31))
        self.label.setObjectName("label")
        self.soundboardvolume_sb = QtWidgets.QSpinBox(Dialog)
        self.soundboardvolume_sb.setGeometry(QtCore.QRect(360, 50, 81, 31))
        self.soundboardvolume_sb.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.soundboardvolume_sb.setMaximum(200)
        self.soundboardvolume_sb.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.soundboardvolume_sb.setObjectName("soundboardvolume_sb")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(480, 50, 171, 31))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))
        self.label.setText(_translate("Dialog", "hear my self volume"))
        self.label_2.setText(_translate("Dialog", "sound board volume"))
